name: Run Selenium Script (Daily)

on:
  schedule:
    - cron: "30 12 * * *"   # 10:00 AM IST (04:30 UTC)
  workflow_dispatch:        # allows manual run

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas openpyxl

      - name: Run Python script
        env:
          PORTAL_USER: ${{ secrets.PORTAL_USER }}
          PORTAL_PASS: ${{ secrets.PORTAL_PASS }}
        run: python myscript.py

      - name: Upload Excel output
        uses: actions/upload-artifact@v4
        with:
          name: excel-output
          path: output/*.xlsx

      -       - name: Send email with attachment
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          secure: starttls
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          to: Dev.bhatia@rattanIndia.com
          from: "GitHub Bot <Dev.bhatia@rattanIndia.com>"
          subject: "Daily Selenium Report"
          body: "Attached is your daily automation Excel file."
          attachments: "output/*.xlsx"

